name: shoesly
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  lottie: ^3.1.2
  flutter_bloc: ^8.1.5
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  simple_animations: ^5.0.2
  flutter_slidable: ^3.1.0
  flutter_map: ^6.1.0
  geocoding: ^3.0.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

# Command for creating native splash
# > dart run flutter_native_splash:create
flutter_native_splash:
  color: "#f3f3f3"
  image: assets/images/logo.png

  android_12:
    color: "#f3f3f3"
    image: assets/images/native_splash_icon_android12.png

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf
